name: Gene Kogan
markdown: kramdown
collections:
  book:
    output: true
    permalink: /ml4a/:path/
  translations:
    output: true
    permalink: /ml4a/:path/
  activities:
    output: true
    permalink: /activities/:path  
  demos:
    output: true
    permalink: /demos/:path/
  pages:
    output: true
    permalink: /:path/
