name: Gene Kogan
markdown: kramdown
collections:
  book:
    output: true
    permalink: /ml4a/:path/
  translations:
    output: true
    permalink: /ml4a/:path/
  activities:
    output: true
    permalink: /activities/:path  
  demo:
    output: true
    permalink: /demo/:path/
  pages:
    output: true
    permalink: /:path/
